/**
 * @file model_data.h
 * @brief Auto-generated baseline model parameters for embedded anomaly detection.
 * Generated by adaptnxt-tinyml export-header.
 */

#ifndef ADAPTNXT_MODEL_DATA_H
#define ADAPTNXT_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

#define VIBRATION_MODEL_VERSION "0.1.0"
#define VIBRATION_THRESHOLD 2.5f

// Baseline means for: [RMS, Peak-to-Peak, Crest Factor, Kurtosis, Dominant Freq (Hz)]
static const float VIBRATION_BASELINE_MEANS[5] = {
    0.707f,   // RMS
    2.000f,   // Peak-to-Peak
    1.414f,   // Crest Factor
    3.000f,   // Kurtosis (Normal Gaussian)
    60.000f   // Dominant Frequency (60 Hz motor fundamental)
};

// Baseline standard deviations
static const float VIBRATION_BASELINE_STDS[5] = {
    0.050f,   // RMS std
    0.150f,   // P2P std
    0.100f,   // Crest factor std
    0.300f,   // Kurtosis std
    2.500f    // Dominant frequency std
};

#ifdef __cplusplus
}
#endif

#endif /* ADAPTNXT_MODEL_DATA_H */
