"""Vibration anomaly detection model and embedded C header generator."""

import numpy as np
from typing import List, Dict, Any, Tuple
from tinyml_vibration.features import VibrationFeatureExtractor


class VibrationAnomalyDetector:
    """One-Class statistical distance anomaly detector deployable on edge microcontrollers."""

    def __init__(self, threshold: float = 2.5):
        self.threshold = threshold
        self.means: np.ndarray = np.array([0.707, 2.0, 1.414, 3.0, 60.0], dtype=np.float32)
        self.stds: np.ndarray = np.array([0.05, 0.15, 0.10, 0.30, 2.5], dtype=np.float32)
        self.feature_names = VibrationFeatureExtractor.FEATURE_NAMES

    def fit(self, normal_feature_vectors: List[np.ndarray], threshold_percentile: float = 99.0):
        """Fits baseline normal distribution and calibrates decision threshold."""
        data = np.vstack(normal_feature_vectors)
        self.means = np.mean(data, axis=0).astype(np.float32)
        self.stds = np.std(data, axis=0).astype(np.float32)
        # Prevent division by zero
        self.stds = np.where(self.stds < 1e-6, 1.0, self.stds)

        scores = [self.score(vec) for vec in normal_feature_vectors]
        self.threshold = float(np.percentile(scores, threshold_percentile))

    def score(self, feature_vector: np.ndarray) -> float:
        """Calculates normalized Z-score Euclidean distance against baseline."""
        z = (feature_vector - self.means) / self.stds
        return float(np.sqrt(np.mean(z ** 2)))

    def predict(self, feature_vector: np.ndarray) -> Tuple[bool, float]:
        """Predicts whether an observation is anomalous."""
        dist = self.score(feature_vector)
        is_anomalous = bool(dist > self.threshold)
        return is_anomalous, dist

    def export_c_header(self, output_path: str, version: str = "0.1.0"):
        """Generates a C99 header file for embedded compilation on ESP32/STM32."""
        means_str = ", ".join([f"{v:.4f}f" for v in self.means])
        stds_str = ", ".join([f"{v:.4f}f" for v in self.stds])

        header_content = f"""/**
 * @file model_data.h
 * @brief Auto-generated baseline model parameters for embedded anomaly detection.
 * Generated by adaptnxt-tinyml export-header.
 */

#ifndef ADAPTNXT_MODEL_DATA_H
#define ADAPTNXT_MODEL_DATA_H

#ifdef __cplusplus
extern "C" {{
#endif

#define VIBRATION_MODEL_VERSION "{version}"
#define VIBRATION_THRESHOLD {self.threshold:.4f}f

// Baseline means: [{', '.join(self.feature_names)}]
static const float VIBRATION_BASELINE_MEANS[{len(self.means)}] = {{
    {means_str}
}};

// Baseline standard deviations
static const float VIBRATION_BASELINE_STDS[{len(self.stds)}] = {{
    {stds_str}
}};

#ifdef __cplusplus
}}
#endif

#endif /* ADAPTNXT_MODEL_DATA_H */
"""
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header_content)
